### ISSUE TITLE
Versioning in logging bucket?

### ISSUE THREAD

**Issue by smiller171** [rhythmictech/terraform-aws-s3logging-bucket#5]
@cdaniluk do we really want to version the logging bucket? This seems counter-intuitive to me

https://github.com/rhythmictech/terraform-aws-s3logging-bucket/blob/f7b9f0d29a5624d952274ffe702d06a04c6a6dd7/main.tf#L13-L15

**Comment by cdaniluk** [comment]
It's a way to prove to auditors that the logs aren't being written. AWS doesn't really have a way to make an object truly immutable once published currently, so this is a hacky way to do that. Maybe it should be parameterized though?
